<?php

namespace App\Controller\Admin;

use App\Controller\Controller;

class User extends Controller
{
    protected function before()
    {
//        parent::before(); // TODO: Change the autogenerated stub
    }

    public function indexAction()
    {
        echo 'indexAction to User controller';
    }
}